language: python
python:
  - "2.6"
  - "2.7"
env:
  - ERP=7 OORQ_DATABASE=oerp7 OORQ_DB_USER=oerp OORQ_DB_HOST=localhost
    OORQ_ADDONS_PATH=${HOME}/src/openerp-server-${ERP}.0/openerp/addons
services:
  - redis-server
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - pip install --no-use-wheel --allow-external -q -r tests/tests_${ERP}_requirements.txt
  - pip install --no-use-wheel -q -r requirements.txt
  - mkdir -p ${HOME}/src
  - pushd ${HOME}/src
  - curl -L https://github.com/akretion/openerp-server/archive/${ERP}.0.tar.gz | tar xvzf -
  - curl -L https://github.com/akretion/openerp-web/archive/${ERP}.0.tar.gz | tar xvzf -
  - cd ${HOME}/src/openerp-server-${ERP}.0/openerp/addons
  - mv ${HOME}/src/openerp-web-${ERP}.0/addons/* .
  - createuser -s ${OORQ_DB_USER}
  - createdb --owner=${OORQ_DB_USER} ${OORQ_DATABASE}
  - cd ../../
  - python setup.py install
  - openerp-server --database=$OORQ_DATABASE --db_host=$OORQ_DB_HOST --db_user=$OORQ_DB_USER --init=all --stop-after-init
  - popd
script:
  - py.test tests/*.py
notifications:
  irc: "irc.freenode.org#gisce-commits"
